# https://hub.docker.com/_/postgres <-- postgres image
services:
  app:
    # to create this image run the following command first:
    # mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=webec-qa-spring:1
    image: webec-qa-spring:1
    restart: always # restart the container if it crashes or if the system reboots or similar
    ports:
      - 8080:8080 # map the port 8080 from the container to the port 8080 on the host